### ISSUE TITLE
Player requests for a game and a seat within that game

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#30]
Add or modify the following 

**Models**
* Waitinglist
  * columns
     - player_id:references
     - game_id:references
     - preferred_seat:integer

* Game
  * ~columns~
    - ~game_is_active:boolean~
  * associations
    - has_many :waitinglists

* Player
  * associations
    - has_many :waitinglists

**Controllers**

* WaitinglistsController
  * create()
    - expect parameters preferred_seat, game_id, and player_id
    -  create a new waitlist object with the above parameters
  * show()
    - return current_player's waiting list
  * destroy()
    - destroy the waitinglist object

**Comment by roxanneeullo** [comment]
Added column `game_is_active` to `Game` table in Issue #29

**Comment by arman-miranda** [comment]
PR #42
