### ISSUE TITLE
Dealer join request acceptance and Player Join acceptance

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#31]
Modify the following

**Controllers**
* WaitinglistsController
  * destroy()
    - add control flow so that it will send a notification to the player that has been denied. No need to implement just add a TODO in place.
  * update()
    - update the is_accepted column to true

* PlayerGameController
   * create()
      - create a player_game object for the user accepted
      - destroy all waitinglist objects associated with the user accepted

**Models**
* Waitinglist
  * Columns
    - is_accepted:boolean

**Comment by roxanneeullo** [comment]
#46
