### ISSUE TITLE
Start Round

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#34]
Modify the following:

**Controllers**
* PlayerRoundsController
  * create()
    - record player selected action
  * show()
    - return a string that would be shown in the game logs
* GamesController
  * round_start()
    - return list of current players

**Models**
* PlayerRound
  * columns
    - round_id:references
    - player_id:references
    - action:string

**Comment by roxanneeullo** [comment]
PR #53
