### ISSUE TITLE
Login page still moves to the next page regardless of Authentication result

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#58]
Writing anything on the login page will let you proceed to other pages

```
handleResponse(response) {
    response.json().then( data => {
      localStorage.setItem('currentUser', JSON.stringify(data))
      this.props.handleUserLogin()
      this.setState({
        isAuthenticated: true
      })
    })
  }
```

I think this piece of code is the culprit, kindly add a condition so that it would not save to localStorage when an error is received

**Comment by marc-fulgar** [comment]
`PR:` https://github.com/arman-miranda/poker-plus-ui-react/pull/10
