### ISSUE TITLE
Transfer card selection logic from player_games#update to card controller

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#70]
Kindly transfer the logic for card selection from this issue: [Issue #39: card selection page](https://github.com/arman-miranda/poker_plus_api/pull/51) to the controller made in this issue: [Feature/issue 33 player card selection](https://github.com/arman-miranda/poker_plus_api/pull/47)

**Comment by marc-fulgar** [comment]
PR #71
