### ISSUE TITLE
Add ActionCable to the pages that needs Real time Updating

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#73]
Some pages seems to have a need to be updated in realtime via ActionCable. Please subscribe the following pages to our ActionCable Implementation:

* Games List(/games)
  - values should update whenever a new game is hosted
* Game Waiting list (/games/:game_id/waitinglist)
  - update whenever someone asks to be added to the game
* Player Waiting list(players/:player_id/waitinglist)

**NOTE:**  Please unsubscribe from the channel used whenever the user leaves the page

**Comment by marc-fulgar** [comment]
PR #74
