### ISSUE TITLE
Add Active Game UI Indications

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#79]
Add the following enhancement to a currently starting game

* Show an alert whenever the user moves to another page or refreshes the current game page that it will result in him folding in the current game

* Disable all buttons(except the dealer exclusive buttons) when game has already started

* Grey out players that are not joining the current game.

**Comment by roxanneeullo** [comment]
PR: arman-miranda/poker-plus-ui-react#21
