### ISSUE TITLE
Prompt for when players leave should not show up to players not playing the game

### ISSUE THREAD

**Issue by arman-miranda** [arman-miranda/poker_plus_api#97]
"This action will automatically fold your current game. Are you sure you want to continue?'

Steps:
- Join an ongoing game
- Select 'Go back to games' button

Expected:
I think this alert should not be appearing at all since I just joined the game the view outcome"

**Comment by roxanneeullo** [comment]
PR arman-miranda/poker-plus-ui-react#30
